version: '3.7'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
      - ./data/backups/mongo:/backups
    restart: unless-stopped

  # redis:
  #   container_name: "redis"
  #   image: redis/redis-stack:latest
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped